/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by ack-generate. DO NOT EDIT.

package workgroup

import (
	"github.com/aws/aws-sdk-go/aws/awserr"
	svcsdk "github.com/aws/aws-sdk-go/service/athena"

	svcapitypes "github.com/crossplane/provider-aws/apis/athena/v1alpha1"
)

// NOTE(muvaf): We return pointers in case the function needs to start with an
// empty object, hence need to return a new pointer.

// GenerateGetWorkGroupInput returns input for read
// operation.
func GenerateGetWorkGroupInput(cr *svcapitypes.WorkGroup) *svcsdk.GetWorkGroupInput {
	res := &svcsdk.GetWorkGroupInput{}

	return res
}

// GenerateWorkGroup returns the current state in the form of *svcapitypes.WorkGroup.
func GenerateWorkGroup(resp *svcsdk.GetWorkGroupOutput) *svcapitypes.WorkGroup {
	cr := &svcapitypes.WorkGroup{}

	return cr
}

// GenerateCreateWorkGroupInput returns a create input.
func GenerateCreateWorkGroupInput(cr *svcapitypes.WorkGroup) *svcsdk.CreateWorkGroupInput {
	res := &svcsdk.CreateWorkGroupInput{}

	if cr.Spec.ForProvider.Configuration != nil {
		f0 := &svcsdk.WorkGroupConfiguration{}
		if cr.Spec.ForProvider.Configuration.BytesScannedCutoffPerQuery != nil {
			f0.SetBytesScannedCutoffPerQuery(*cr.Spec.ForProvider.Configuration.BytesScannedCutoffPerQuery)
		}
		if cr.Spec.ForProvider.Configuration.EnforceWorkGroupConfiguration != nil {
			f0.SetEnforceWorkGroupConfiguration(*cr.Spec.ForProvider.Configuration.EnforceWorkGroupConfiguration)
		}
		if cr.Spec.ForProvider.Configuration.EngineVersion != nil {
			f0f2 := &svcsdk.EngineVersion{}
			if cr.Spec.ForProvider.Configuration.EngineVersion.EffectiveEngineVersion != nil {
				f0f2.SetEffectiveEngineVersion(*cr.Spec.ForProvider.Configuration.EngineVersion.EffectiveEngineVersion)
			}
			if cr.Spec.ForProvider.Configuration.EngineVersion.SelectedEngineVersion != nil {
				f0f2.SetSelectedEngineVersion(*cr.Spec.ForProvider.Configuration.EngineVersion.SelectedEngineVersion)
			}
			f0.SetEngineVersion(f0f2)
		}
		if cr.Spec.ForProvider.Configuration.PublishCloudWatchMetricsEnabled != nil {
			f0.SetPublishCloudWatchMetricsEnabled(*cr.Spec.ForProvider.Configuration.PublishCloudWatchMetricsEnabled)
		}
		if cr.Spec.ForProvider.Configuration.RequesterPaysEnabled != nil {
			f0.SetRequesterPaysEnabled(*cr.Spec.ForProvider.Configuration.RequesterPaysEnabled)
		}
		if cr.Spec.ForProvider.Configuration.ResultConfiguration != nil {
			f0f5 := &svcsdk.ResultConfiguration{}
			if cr.Spec.ForProvider.Configuration.ResultConfiguration.EncryptionConfiguration != nil {
				f0f5f0 := &svcsdk.EncryptionConfiguration{}
				if cr.Spec.ForProvider.Configuration.ResultConfiguration.EncryptionConfiguration.EncryptionOption != nil {
					f0f5f0.SetEncryptionOption(*cr.Spec.ForProvider.Configuration.ResultConfiguration.EncryptionConfiguration.EncryptionOption)
				}
				if cr.Spec.ForProvider.Configuration.ResultConfiguration.EncryptionConfiguration.KMSKey != nil {
					f0f5f0.SetKmsKey(*cr.Spec.ForProvider.Configuration.ResultConfiguration.EncryptionConfiguration.KMSKey)
				}
				f0f5.SetEncryptionConfiguration(f0f5f0)
			}
			if cr.Spec.ForProvider.Configuration.ResultConfiguration.OutputLocation != nil {
				f0f5.SetOutputLocation(*cr.Spec.ForProvider.Configuration.ResultConfiguration.OutputLocation)
			}
			f0.SetResultConfiguration(f0f5)
		}
		res.SetConfiguration(f0)
	}
	if cr.Spec.ForProvider.Description != nil {
		res.SetDescription(*cr.Spec.ForProvider.Description)
	}
	if cr.Spec.ForProvider.Name != nil {
		res.SetName(*cr.Spec.ForProvider.Name)
	}
	if cr.Spec.ForProvider.Tags != nil {
		f3 := []*svcsdk.Tag{}
		for _, f3iter := range cr.Spec.ForProvider.Tags {
			f3elem := &svcsdk.Tag{}
			if f3iter.Key != nil {
				f3elem.SetKey(*f3iter.Key)
			}
			if f3iter.Value != nil {
				f3elem.SetValue(*f3iter.Value)
			}
			f3 = append(f3, f3elem)
		}
		res.SetTags(f3)
	}

	return res
}

// GenerateUpdateWorkGroupInput returns an update input.
func GenerateUpdateWorkGroupInput(cr *svcapitypes.WorkGroup) *svcsdk.UpdateWorkGroupInput {
	res := &svcsdk.UpdateWorkGroupInput{}

	if cr.Spec.ForProvider.Description != nil {
		res.SetDescription(*cr.Spec.ForProvider.Description)
	}

	return res
}

// GenerateDeleteWorkGroupInput returns a deletion input.
func GenerateDeleteWorkGroupInput(cr *svcapitypes.WorkGroup) *svcsdk.DeleteWorkGroupInput {
	res := &svcsdk.DeleteWorkGroupInput{}

	return res
}

// IsNotFound returns whether the given error is of type NotFound or not.
func IsNotFound(err error) bool {
	awsErr, ok := err.(awserr.Error)
	return ok && awsErr.Code() == "InvalidRequestException"
}
